catalog/urls.py
from django.urls import path
from . import views


app_name = "catalog"

urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book_detail"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author_detail"),
]

locallibrary/urls.py
from distutils.debug import DEBUG
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from ast import arg
import uuid
from django.db import models
from django.urls import reverse

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a book genre (e.g Fiction)")

    def __str__(self) -> str:
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        return reverse("catalog:author_detail", args=[str(self.id)])

    def __str__(self) -> str:
        return f"{self.last_name}, {self.first_name}"


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text="3 Character <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>",
    )
    genre = models.ManyToManyField(Genre, help_text="select a genre for this book")

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse("catalog:book_detail", args=[str(self.id)])

    def display_genre(self):
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, help_text="Unique id for this particular book across whoel library"
    )
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1, choices=LOAN_STATUS, blank=True, default="m", help_text="Book availability"
    )

    class Meta:
        ordering = ["due_back"]

    def __str__(self) -> str:
        return f"{self.id} ({self.book.title})"

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Author, Book, BookInstance, Genre

# Create your views here.
def index(request):
    """View function for home page of site"""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = "a")
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()

    num_authors = Author.objects.count()
    num_sci_genre = Book.objects.filter(genre__name__icontains="science").count()
    num_of_book_contain_war = Book.objects.filter(title__icontains="war").count()

    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_sci_genre": num_sci_genre,
        "num_sci_genre": num_sci_genre,
        "num_of_book_contain_war": num_of_book_contain_war,
    }

    return render(request, "index.html", context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Local Library{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'catalog:index' %}">Home</a></li>
                    <li><a href="{% url 'catalog:books' %}">All books</a></li>
                    <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}
                {% endblock %}

                {% block pagination %}
                {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %}Author Detail{% endblock %}

{% block content %}
<h1>Author: {{author.last_name}}, {{author.first_name}}</h1>
<p>{{author.date_of_birth}}</p>

<div style="margin-left:20px;margin-top:20px">
    <p> Books</p>

    {% for book in author.book_set.all %}
    <strong><a href="{{ book.get_absolute_url }}">{{ book.title }}</a>({{book.id}})</strong>
    <p>{{book.summary}}</p>

    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title %}Authors{% endblock %}


{% block content %}
<h1>Author List</h1>
{% if author_list %}
<ul>
    {% for author in author_list %}
    <li>
        <a href="{{author.get_absolute_url}}">{{ author.first_name }}, {{author.last_name}}
            ({{author.date_of_birth}}) </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no authors in the library yet</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %}Book Detail{% endblock %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
<!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block title %}Book List{% endblock %}
{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}


{% block title%}Home{% endblock %}

{% block content %}
<h1>Local Library Home</h1>
<p>Welcome to LocalLibrary, a website developed by <em>Baronial AgTech Team</em>!</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Science genre books:</strong> {{ num_sci_genre }}</li>
    <li><strong>Books that contains the word 'war':</strong> {{ num_sci_genre }}</li>
</ul>
{% endblock %}